repos:
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "1.1.0"
  hooks:
    - id: sync_with_poetry
- repo: https://github.com/asottile/pyupgrade # only enable after all services on python3.12
  rev: v3.15.2
  hooks:
  - id: pyupgrade

- repo: https://github.com/myint/autoflake
  rev: v2.3.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/myint/docformatter
  rev: v1.7.5 # don't upgrade not compatible with isort
  hooks:
    - id: docformatter
      args: ['--in-place', '--wrap-summaries=120', '--wrap-descriptions=120', '--pre-summary-newline']

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      exclude: ^tests/.*/fixtures/.*
    - id: end-of-file-fixer
      exclude: ^tests/.*/fixtures/.*
    - id: debug-statements
    - id: check-yaml
    - id: double-quote-string-fixer
    - id: detect-private-key
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: ['--fix=lf']
    # - id: no-commit-to-branch
    #   args: [-b, "master"]
    - id: check-docstring-first

- repo: local
  hooks:
    - id: check_indents
      name: check_indents
      language: system
      types: [file, python]
      entry: poetry run python3 bin/check_indents.py

    - id: isort
      name: isort
      exclude: ^.*/?setup\.py$
      language: system
      types: [file, python]
      entry: poetry run isort

    - id: black
      name: black
      language: system
      types: [file, python]
      entry: poetry run black

    - id: flake8
      name: flake8
      language: python
      types: [file, python]
      entry: poetry run flake8
      additional_dependencies: [
            'flake8-blind-except',
            'flake8-comprehensions',
            'flake8-deprecated',
            'flake8-docstrings',
            'flake8-bugbear', # need to fix all warnings
            'flake8-pep3101',
            'flake8-quotes',
            'flake8-string-format',
            'flake8-tidy-imports',
      ]

    - id: unittest
      name: unittest
      language: system
      types: [file, python]
      pass_filenames: false
      entry: poetry run nox -r

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.0.3
  hooks:
    - id: sqlfluff-lint
    - id: sqlfluff-fix
