# put your secret values and credentials here. do not share this file and do not push it to github

[destination.filesystem]
# bucket_url = "gs://..." # replace with your bucket name,
bucket_url = "file://dlt_data" # two / for a relative path
layout="{table_name}/{load_id}.{file_id}.{ext}" # current preconfigured naming scheme

[destination.filesystem.credentials]
# project_id = "" # please set me up!
# private_key = "" # please set me up!
# client_email = "" # please set me up!
